version: "3"
services:
    rails:
        build: .
        container_name: "rails-dev"
        stdin_open: true
        tty: true
        volumes:
            - ./code:/code
        ports:
            - "3000:3000"
